name: Build

on: [push, pull_request]

jobs:
  debian:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/cache@v3
        with:
          path: |
            stockfish/vendor/sde-external-9.0.0-2021-11-07-lin.tar.xz
            stockfish/vendor/x86_64-linux-musl-native.tgz
            stockfish/vendor/sf_15.tar.gz
            stockfish/vendor/nn-6877cd24400e.nnue
          key: ${{ runner.os }}-stockfish-${{ hashFiles('stockfish/vendor/SHA256SUM') }}
      - run: ./deps.sh
      - uses: docker/setup-buildx-action@v1
      - uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          cache-from: type=gha
          cache-to: type=gha
          load: true
          tags: niklasf/external-engine:latest
      - run: docker cp "$(docker create niklasf/external-engine):/stockfish_15-1_amd64.deb" .
      - run: docker cp "$(docker create niklasf/external-engine):/remote-uci_1-1_amd64.deb" .
      - uses: actions/upload-artifact@v3
        with:
          name: external-engine-debian
          path: |
            stockfish_15-1_amd64.deb
            remote-uci_1-1_amd64.deb
  windows:
    runs-on: windows-2019
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          install: mingw-w64-x86_64-gcc mingw-w64-x86_64-rust mingw-w64-x86_64-make tar
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/checkout@v3
        with:
          repository: lichess-org/intel-sde
          ssh-key: ${{ secrets.ID_RSA_INTEL_SDE }}
          ref: main
          path: intel-sde
        id: sde
        continue-on-error: true
      - run: |
          tar xf intel-sde/sde-external-9.0.0-2021-11-07-win.tar.xz && echo SDE_PATH=$(cygpath -u $GITHUB_WORKSPACE)/sde-external-9.0.0-2021-11-07-win/sde.exe | tee $GITHUB_ENV
          echo PGO=profile- | tee $GITHUB_ENV
        if: steps.sde.outcome == 'success'
      - run: |
          cd stockfish/vendor/Stockfish/src
          CXXFLAGS=-DNNUE_EMBEDDING_OFF mingw32-make -B -j2 ${PGO}build COMP=mingw CXX=g++ ARCH=x86-64 EXE=stockfish-x86-64.exe
          mingw32-make strip EXE=stockfish-x86-64.exe
          CXXFLAGS=-DNNUE_EMBEDDING_OFF mingw32-make -B -j2 ${PGO}build COMP=mingw CXX=g++ ARCH=x86-64-sse3-popcnt EXE=stockfish-x86-64-sse3-popcnt.exe
          mingw32-make strip EXE=stockfish-x86-64-sse3-popcnt.exe
          CXXFLAGS=-DNNUE_EMBEDDING_OFF mingw32-make -B -j2 ${PGO}build COMP=mingw CXX=g++ ARCH=x86-64-ssse3 EXE=stockfish-x86-64-ssse3.exe
          mingw32-make strip EXE=stockfish-x86-64-ssse3.exe
          CXXFLAGS=-DNNUE_EMBEDDING_OFF mingw32-make -B -j2 ${PGO}build COMP=mingw CXX=g++ ARCH=x86-64-sse41-popcnt EXE=stockfish-x86-64-sse41-popcnt.exe
          mingw32-make strip EXE=stockfish-x86-64-sse41-popcnt.exe
          CXXFLAGS=-DNNUE_EMBEDDING_OFF mingw32-make -B -j2 ${PGO}build COMP=mingw CXX=g++ ARCH=x86-64-avx2 EXE=stockfish-x86-64-avx2.exe
          mingw32-make strip EXE=stockfish-x86-64-avx2.exe
          CXXFLAGS=-DNNUE_EMBEDDING_OFF mingw32-make -B -j2 ${PGO}build COMP=mingw CXX=g++ ARCH=x86-64-bmi2 EXE=stockfish-x86-64-bmi2.exe
          mingw32-make strip EXE=stockfish-x86-64-bmi2.exe
          CXXFLAGS=-DNNUE_EMBEDDING_OFF mingw32-make -B -j2 ${PGO}build COMP=mingw CXX=g++ ARCH=x86-64-avx512 EXE=stockfish-x86-64-avx512.exe
          mingw32-make strip EXE=stockfish-x86-64-avx512.exe
          CXXFLAGS=-DNNUE_EMBEDDING_OFF mingw32-make -B -j2 ${PGO}build COMP=mingw CXX=g++ ARCH=x86-64-vnni512 EXE=stockfish-x86-64-vnni512.exe
          mingw32-make strip EXE=stockfish-x86-64-vnni512.exe
          cp stockfish-* ../../../../remote-uci-service/wix/
          cp nn-*.nnue ../../../../remote-uci-service/wix/
      - run: cargo install cargo-wix
      - run: |
          cd remote-uci-service
          cargo wix --nocapture --package remote-uci-service -l wix/main.wxl
      - uses: actions/upload-artifact@v3
        with:
          name: external-engine-windows
          path: target/wix/remote-uci-*.msi
  debian-release:
    runs-on: ubuntu-latest
    needs:
      - debian
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
      - run: sudo apt-get install -y reprepro
      - run: reprepro --basedir gh-pages/debian includedeb bullseye external-engine/stockfish_15-1_amd64.deb
      - run: reprepro --basedir gh-pages/debian includedeb bullseye external-engine/remote-uci_1-1_amd64.deb
      - run: |
          cd gh-pages &&
          git init --initial-branch gh-pages &&
          git config user.name "${GITHUB_ACTOR}" &&
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com" &&
          git add . &&
          git commit -m 'Display to GitHub Pages' &&
          git push --force "https://${GH_PAT}@github.com/${GITHUB_REPOSITORY}.git" gh-pages
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
  windows-release:
    runs-on: ubuntu-latest
    needs:
      - windows
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/download-artifact@v3
      - uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: External engine ${{ github.ref }}
          draft: true
          prerelease: false
        id: create_release
      - uses: actions/update-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: remote-uci-*.msi
          asset_name: remote-uci.msi
          asset_content_type: application/octet-stream
