name: Build

on: [push, pull_request]

jobs:
  debian:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: ./deps.sh
      - uses: docker/setup-buildx-action@v1
      - uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          cache-from: type=gha
          cache-to: type=gha
          load: true
          tags: niklasf/external-engine:latest
      - run: docker cp "$(docker create niklasf/external-engine):/stockfish_15-1_amd64.deb" .
      - run: docker cp "$(docker create niklasf/external-engine):/remote-uci_1-1_amd64.deb" .
      - uses: actions/upload-artifact@v3
        with:
          name: external-engine-debian
          path: |
            stockfish_*_amd64.deb
