name: Build

on: [push, pull_request]

jobs:
  stockfish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            stockfish/sde-external-9.0.0-2021-11-07-lin.tar.xz
            stockfish/x86_64-linux-musl-native.tgz
            stockfish/sf_15.tar.gz
            stockfish/nn-6877cd24400e.nnue
          key: ${{ runner.os }}-stockfish-${{ hashFiles('stockfish/SHA256SUM') }}
      - run: wget --no-clobber --input-file downloads.txt
        working-directory: stockfish
      - uses: docker/setup-buildx-action@v1
      - uses: docker/build-push-action@v3
        with:
          context: stockfish
          file: stockfish/Dockerfile
          cache-from: type=gha
          cache-to: type=gha
          load: true
          tags: stockfish
      - run: docker cp stockfish:/stockfish_15-1_amd64.deb .
      - uses: actions/upload-artifact@v3
        with:
          name: stockfish
          path: stockfish_15-1_amd64.deb
